name: Demo Pipeline 

on:
    push:
        branches:
        - main
    pull_request:
        branches: [main , dev ]
    schedule: 
    - cron: "*/1 * * * *"  # Runs every Sunday at midnight

jobs:
    setup_jobs:
        runs-on: ubuntu-latest #macos-latest , Windows-latest, 
        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v3 
            
            - name: Create File
              run: touch githubaction.txt
            - name: Print Hello World
              run:  echo "Hello, World!"
            - name: Display README 
              run: cat README.md

     
    build_job:
        needs: setup_jobs
        runs-on: ubuntu-latest
       
        steps:
            - name: Display Hello
              run: echo "Hello"
            - name: Display Github-action.txt
              run: |
               cat githubaction.txt
               ls -la

    deploy_job:
        needs: build_job
        runs-on: macos-latest
        steps:
         - run: echo "Hello Mac"