name: Demo Pipeline 

on:
    push:
        branches:
        - main
    pull_request:
        branches: [main , dev ]
    schedule: 
    - cron: "*/1 * * * *"  # Runs every Sunday at midnight

jobs:
    setup_jobs:
        runs-on: ubuntu-latest #macos-latest , Windows-latest, 
        steps:
            - name: Create File
              run: touch githubaction.txt
            - name: Print Hello World
              run:  echo "Hello, World!"
            - name: Display README 
              run: cat README.md

     
    build_job:
        runs-on: ubuntu-latest
        needs: setup_jobs
        steps:
            - name: Display Hello
              run: echo "Hello"

    deploy_job:
        runs-on: macos-latest
        steps:
         - run: echo "Hello Mac"